grafana:
  adminPassword: admin123
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: selfsigned-issuer
    hosts:
      - grafana.localhost
    path: /
    pathType: Prefix
    tls:
      - secretName: grafana-localhost-tls
        hosts:
          - grafana.localhost

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true
