grafana:
  adminPassword: admin123
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.localhost
    path: /
    pathType: Prefix

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true
