apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - rabbitmq-ingress.yaml

patches:
  - path: frontend-html-patch.yaml
  - path: frontend-tls-patch.yaml
  - target:
      kind: Ingress
      name: frontend
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: ecommerce-dev.localhost
