apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-management
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - rabbitmq-dev.localhost
      secretName: rabbitmq-dev-localhost-tls
  rules:
    - host: rabbitmq-dev.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 15672
