apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami-dev
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/nazeem2906/ecom-platform-gitops.git
    targetRevision: main
    path: gitops/apps/whoami-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
