apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-staging
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/nazeem2906/ecom-platform-gitops.git
    targetRevision: main
    path: apps/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
