apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis.yaml
  - productcatalog.yaml
  - frontend-configmap.yaml
  - frontend-service.yaml
  - rabbitmq.yaml
  - worker.yaml
