apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalog
  template:
    metadata:
      labels:
        app: productcatalog
    spec:
      containers:
        - name: productcatalog
          image: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice:v0.10.5
          ports:
            - containerPort: 3550
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalog
spec:
  selector:
    app: productcatalog
  ports:
    - port: 3550
      targetPort: 3550
